- import_tasks: daemon.yaml
- import_tasks: volume.yaml

- name: Enable IOMMU in Linux command line
  become: yes
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    insertbefore: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on"'
  register: grub_configuration_file

- name: Update GRUB configuration
  become: yes
  command: update-grub
  when: grub_configuration_file.changed

- name: Reboot system
  become: yes
  reboot:
  when: grub_configuration_file.changed

- name: Copy vision udev rules
  become: yes
  copy:
    dest: /etc/udev/rules.d/99-vision.rules
    src: udev/vision.rules

- name: Create `/opt/vision` directory
  become: yes
  file: path=/opt/vision state=directory

- name: Copy each vision script
  become: yes
  copy: dest=/opt/vision/{{ item | basename }} src={{ item }}
  loop:
  - script/device_to_device_is
  - script/dump_environment
  - script/save_device
