- name: Update hostname
  become: yes
  hostname: name={{ inventory_hostname }}

- name: Allow sudo without a password or TTY
  become: yes
  copy: dest=/etc/sudoers.d/sudo src=sudo mode=0440

- name: Ensure `/etc/apt/apt.conf.d` is available
  become: yes
  file: path=/etc/apt/apt.conf.d state=directory

- name: Install minimalist configuration for APT
  become: yes
  copy: dest=/etc/apt/apt.conf.d/99minimalist src=minimalist

- name: Autoremove unnecessary packages
  become: yes
  apt: autoremove=yes

- name: Install neovim
  become: yes
  apt: name=neovim

- name: Install Git
  become: yes
  apt: name=git

- name: Install make
  become: yes
  apt: name=make

- name: Create a user account for each person
  become: yes
  user: name={{ item.username }}
  loop: "{{ people }}"

- name: Enable `sudo` access for each person
  become: yes
  user: name={{ item.username }} append=yes groups=sudo
  loop: "{{ people }}"

- name: Add each person's list of authorized keys
  become: yes
  authorized_key: user={{ item.0.username }} key={{ item.1 }}
  loop: "{{ people | subelements('authorized_keys', skip_missing=True) }}"
