- name: Install QEMU-KVM
  become: yes
  apt: name=qemu-kvm

- name: Copy `kvm` module configuration
  become: yes
  copy: dest=/etc/modprobe.d/kvm.conf src=kvm.conf
  register: kvm_conf

- block:
  - name: Unload `kvm` module
    become: yes
    modprobe: name=kvm state=absent
  - name: Load `kvm` module
    become: yes
    modprobe: name=kvm
  rescue:
  - fail:
      msg: Failed to reload `kvm` module on configuration change. Please reload the module manually or reboot the system.
    ignore_errors: yes
  when: kvm_conf.changed
