- name: Install QEMU-KVM
  become: yes
  apt: name=qemu-kvm

- name: Install virtualization utilities
  become: yes
  apt:
    name:
    - libosinfo-bin # osinfo-query
    - ovmf          # UEFI
    - qemu-utils    # qemu-img
    - virtinst      # virt-install

- name: Copy `kvm` module configuration
  become: yes
  copy: dest=/etc/modprobe.d/kvm.conf src=kvm.conf
  register: kvm_conf

- block:
  - name: Unload `kvm` module
    become: yes
    modprobe: name=kvm state=absent
  - name: Load `kvm` module
    become: yes
    modprobe: name=kvm
  rescue:
  - fail:
      msg: Failed to reload `kvm` module on configuration change. Please reload the module manually or reboot the system.
    ignore_errors: yes
  when: kvm_conf.changed

- name: Install libvirt daemon system
  become: yes
  apt: name=libvirt-daemon-system
  register: libvirtd_package
  notify: Restart libvirt daemon service

- name: Reload `systemd` configuration
  become: yes
  systemd: daemon_reload=yes
  when: libvirtd_package.changed

- name: Enable and start libvirt daemon service
  become: yes
  systemd: name=libvirtd enabled=yes state=started
  register: libvirtd_service
